# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/manh/Documents/mclib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/manh/Documents/mclib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/manh/Documents/mclib/CMakeFiles /home/manh/Documents/mclib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/manh/Documents/mclib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clibraries

# Build rule for target.
clibraries: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clibraries
.PHONY : clibraries

# fast build rule for target.
clibraries/fast:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/build
.PHONY : clibraries/fast

src/base.o: src/base.c.o

.PHONY : src/base.o

# target to build an object file
src/base.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/base.c.o
.PHONY : src/base.c.o

src/base.i: src/base.c.i

.PHONY : src/base.i

# target to preprocess a source file
src/base.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/base.c.i
.PHONY : src/base.c.i

src/base.s: src/base.c.s

.PHONY : src/base.s

# target to generate assembly for a file
src/base.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/base.c.s
.PHONY : src/base.c.s

src/data.o: src/data.c.o

.PHONY : src/data.o

# target to build an object file
src/data.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/data.c.o
.PHONY : src/data.c.o

src/data.i: src/data.c.i

.PHONY : src/data.i

# target to preprocess a source file
src/data.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/data.c.i
.PHONY : src/data.c.i

src/data.s: src/data.c.s

.PHONY : src/data.s

# target to generate assembly for a file
src/data.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/data.c.s
.PHONY : src/data.c.s

src/image.o: src/image.c.o

.PHONY : src/image.o

# target to build an object file
src/image.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/image.c.o
.PHONY : src/image.c.o

src/image.i: src/image.c.i

.PHONY : src/image.i

# target to preprocess a source file
src/image.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/image.c.i
.PHONY : src/image.c.i

src/image.s: src/image.c.s

.PHONY : src/image.s

# target to generate assembly for a file
src/image.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/image.c.s
.PHONY : src/image.c.s

src/list.o: src/list.c.o

.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/list.c.s
.PHONY : src/list.c.s

src/map.o: src/map.c.o

.PHONY : src/map.o

# target to build an object file
src/map.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/map.c.o
.PHONY : src/map.c.o

src/map.i: src/map.c.i

.PHONY : src/map.i

# target to preprocess a source file
src/map.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/map.c.i
.PHONY : src/map.c.i

src/map.s: src/map.c.s

.PHONY : src/map.s

# target to generate assembly for a file
src/map.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/map.c.s
.PHONY : src/map.c.s

src/math.o: src/math.c.o

.PHONY : src/math.o

# target to build an object file
src/math.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/math.c.o
.PHONY : src/math.c.o

src/math.i: src/math.c.i

.PHONY : src/math.i

# target to preprocess a source file
src/math.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/math.c.i
.PHONY : src/math.c.i

src/math.s: src/math.c.s

.PHONY : src/math.s

# target to generate assembly for a file
src/math.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/math.c.s
.PHONY : src/math.c.s

src/node.o: src/node.c.o

.PHONY : src/node.o

# target to build an object file
src/node.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/node.c.o
.PHONY : src/node.c.o

src/node.i: src/node.c.i

.PHONY : src/node.i

# target to preprocess a source file
src/node.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/node.c.i
.PHONY : src/node.c.i

src/node.s: src/node.c.s

.PHONY : src/node.s

# target to generate assembly for a file
src/node.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/node.c.s
.PHONY : src/node.c.s

src/serialize.o: src/serialize.c.o

.PHONY : src/serialize.o

# target to build an object file
src/serialize.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/serialize.c.o
.PHONY : src/serialize.c.o

src/serialize.i: src/serialize.c.i

.PHONY : src/serialize.i

# target to preprocess a source file
src/serialize.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/serialize.c.i
.PHONY : src/serialize.c.i

src/serialize.s: src/serialize.c.s

.PHONY : src/serialize.s

# target to generate assembly for a file
src/serialize.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/serialize.c.s
.PHONY : src/serialize.c.s

src/shader.o: src/shader.c.o

.PHONY : src/shader.o

# target to build an object file
src/shader.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/shader.c.o
.PHONY : src/shader.c.o

src/shader.i: src/shader.c.i

.PHONY : src/shader.i

# target to preprocess a source file
src/shader.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/shader.c.i
.PHONY : src/shader.c.i

src/shader.s: src/shader.c.s

.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/shader.c.s
.PHONY : src/shader.c.s

src/string.o: src/string.c.o

.PHONY : src/string.o

# target to build an object file
src/string.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/string.c.o
.PHONY : src/string.c.o

src/string.i: src/string.c.i

.PHONY : src/string.i

# target to preprocess a source file
src/string.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/string.c.i
.PHONY : src/string.c.i

src/string.s: src/string.c.s

.PHONY : src/string.s

# target to generate assembly for a file
src/string.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/string.c.s
.PHONY : src/string.c.s

src/utils.o: src/utils.c.o

.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) -f CMakeFiles/clibraries.dir/build.make CMakeFiles/clibraries.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... clibraries"
	@echo "... src/base.o"
	@echo "... src/base.i"
	@echo "... src/base.s"
	@echo "... src/data.o"
	@echo "... src/data.i"
	@echo "... src/data.s"
	@echo "... src/image.o"
	@echo "... src/image.i"
	@echo "... src/image.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/math.o"
	@echo "... src/math.i"
	@echo "... src/math.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/serialize.o"
	@echo "... src/serialize.i"
	@echo "... src/serialize.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... src/string.o"
	@echo "... src/string.i"
	@echo "... src/string.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

